### ISSUE TITLE
Change Zotero Client 5.0 Configuration

### ISSUE THREAD

**Issue by dijbi** [mrtcode/zotero-server#2]
Hi,

First of all thanks for the great work making Zotero one of the best tools in academics.
I was testing the Docker config you put up.
I can not figure out how to change the Zotero Client Configuration.
I've tried to go into the Advanced Preferences inside the standalone Zotero app, but i couldn't find preferences to change, walk around the AppData/Zotero folder on W10...

Do I have to rebuild to standalone app ?
Thx !

**Comment by mrtcode** [comment]
Hey @dijbi. Nice to hear that you found Zotero useful!

Yes you have to configure `API_URL`  in [config.js](https://github.com/zotero/zotero/blob/b6065a7af6f264ed2cca37d89879ee20ced884f0/resource/config.js#L12) and rebuild Zotero client. But I must say that `zotero-server` is currently for development purposes only and can't be used in production because it's unstable and incomlete.

**Comment by dijbi** [comment]
Ok, thanks a lot !
